= Contributing to Spring Tools 4

Spring Tools 4 is released under the Eclipse Public License 1.0 (EPL). If you would like to contribute
something, or simply want to hack on the code this document should help you get started.

== Code of Conduct
This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of
conduct]. By participating, you are expected to uphold this code. Please report
unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Using GitHub issues
We use GitHub issues to track bugs and enhancements. If you have a general usage question
please ask on https://stackoverflow.com[Stack Overflow]. The Spring Tools 4 team and the
broader community monitor the https://stackoverflow.com/tags/spring-tools-4[`spring-tools-4`]
tag.

== Sign the Contributor License Agreement
Before we accept a non-trivial patch or pull request we will need you to
https://cla.pivotal.io/sign/sts[sign the Contributor License Agreement].
Signing the contributor's agreement does not grant anyone commit rights to the main
repository, but it does mean that we can accept your contributions, and you will get an
author credit if we do.  Active contributors might be asked to join the core team, and
given the ability to merge pull requests.

== Code Conventions and Housekeeping
None of these is essential for a pull request, but they will all help.  They can also be
added after the original pull request but before a merge.

* Make sure all new source files to have a simple class comment with at least an
  `@author` tag identifying you, and preferably at least a paragraph on what the class is
  for.
* Add the EPL license header comment to all new source files (copy from existing files
  in the project)
* Add yourself as an `@author` to the source files that you modify substantially (more
  than cosmetic changes).
* Add some docs.
* A few unit tests would help a lot as well -- someone has to do it.
* If no-one else is using your branch, please rebase it against the current master (or
  other target branch in the main project).
* When writing a commit message please follow https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions],
  if you are fixing an existing issue please add `Fixes gh-XXXX` at the end of the commit
  message (where `XXXX` is the issue number).
