/*******************************************************************************
 * Copyright (c) 2017 Pivotal, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Pivotal, Inc. - initial API and implementation
 *******************************************************************************/
package org.springframework.ide.vscode.manifest.yaml;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTarget;
import org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.CFTargetCache;
import org.springframework.ide.vscode.commons.cloudfoundry.client.cftarget.NoTargetsException;
import org.springframework.ide.vscode.commons.util.Assert;
import org.springframework.ide.vscode.commons.util.ExceptionUtil;
import org.springframework.ide.vscode.commons.yaml.schema.YValueHint;

public abstract class AbstractCFHintsProvider implements Callable<Collection<YValueHint>> {

	public static final String EMPTY_VALUE = "";
	protected final CFTargetCache targetCache;

	private static final Logger logger = Logger.getLogger(AbstractCFHintsProvider.class.getName());

	public AbstractCFHintsProvider(CFTargetCache targetCache) {
		Assert.isNotNull(targetCache);
		this.targetCache = targetCache;
	}

	@Override
	public Collection<YValueHint> call() throws Exception {
		Collection<YValueHint> hints = new ArrayList<>();
		try {
			List<CFTarget> targets = targetCache.getOrCreate();
			Collection<YValueHint> resolvedHints = getHints(targets);
			if (resolvedHints != null) {
				hints.addAll(resolvedHints);
			}
		} catch (Throwable e) {
			// Convert any non "no-target" errors to something readable. The
			// "no-target" errors
			// are generated by the target provider so they should be propagated
			// as is without further
			// transformation
			if (ExceptionUtil.getThrowable(e, NoTargetsException.class) == null) {
				// Log any other error
				logger.log(Level.SEVERE, e.getMessage(), e);

				if (ExceptionUtil.getThrowable(e, IOException.class) != null) {
					throw ExceptionUtil.asValueParseException(
							"Connection failure to Cloud Foundry. Please check the log for more details.");

				} else {
					throw ExceptionUtil.asValueParseException(
							"Failed to fetch values from Cloud Foundry. Please check the log for more details.");
				}
			}
			else {
				throw e;
			}
		}
		return hints;
	}

	/**
	 * 
	 * @return non-null list of hints. Return empty if no hints available
	 */
	abstract protected Collection<YValueHint> getHints(List<CFTarget> targets) throws Exception;

}
